---
title: "R Notebook"
output: html_notebook
---


# metadata
```{r}
sampels_metadata <- read_tsv("metadata/samples_metadata_imm_272S_long.tsv")

paired_ID <- count(samples_metadata, ID) %>% filter(n==2) %>% select(ID) %>% as.list()

samples_metadata_paired <-
    samples_metadata %>% filter(ID %in% paired_ID$ID)
```


# Species profile
## read species profile
```{r}
tax_file <- "data/metaphlan3.merged.abundance.profile.species.272S.tsv"
tax_s <- read_tsv(tax_file)
tax_s_l <-
    tax_s %>%
    rowwise() %>%
    mutate(Species=str_split(clade_name, "\\|s__")[[1]][2]) %>%
    ungroup() %>%
    pivot_longer(
        names_to="sample_id",
        values_to="Abundance",
        -c(clade_name, Species))

tax_s_l_272S <- tax_s_l %>% inner_join(samples_metadata)
```

## SinoVac
### LEfSe analysis with SinoVac group
```{r}
tax_s_l_m1_sinovac_sVNT_60percent_binary_group <-
    tax_s_l_272S %>%
    filter(TimePoint=="M1") %>%
    filter(Vac_Group=="SinoVac") %>%
    select(sample_id, Species, Abundance, sVNT_60percent_binary_group) %>%
    group_by(Species) %>%
    mutate(Species_abun_sum=sum(Abundance)) %>%
    filter(!Species_abun_sum<=0.0) %>%
    select(-Species_abun_sum) %>%
    ungroup()

tax_s_l_m1_sinovac_sVNT_60percent_binary_group_2 <-
    tax_s_l_m1_sinovac_sVNT_60percent_binary_group %>%
    select(sample_id, sVNT_60percent_binary_group) %>%
    distinct() %>%
    mutate(Species="sVNT_60percent_binary_group") %>%
    rename(Abundance=sVNT_60percent_binary_group) %>%
    mutate(Abundance=as.numeric(Abundance))

tax_s_l_m1_sinovac_sVNT_60percent_binary_group_w <-
    tax_s_l_m1_sinovac_sVNT_60percent_binary_group_2 %>%
    bind_rows(tax_s_l_m1_sinovac_sVNT_60percent_binary_group %>%
    select(sample_id, Species, Abundance)) %>%
    pivot_wider(names_from=sample_id, values_from=Abundance)
    
print(dim(tax_s_l_m1_sinovac_sVNT_60percent_binary_group_w))
write_tsv(tax_s_l_m1_sinovac_sVNT_60percent_binary_group_w,
          "tables/lefse/tax_s_lefse_M1_sinovac_sVNT_60percent_binary_group_w.tsv")
```

### run LEfSe
```{bash}
lefse_format_input.py \
tables/lefse/tax_s_lefse_M1_sinovac_sVNT_60percent_binary_group_w.tsv \
tables/lefse/tax_s_lefse_M1_sinovac_sVNT_60percent_binary_group_w.lefse.in  \
-c 2 -u 1 -o 1000000

lefse_run.py \
tables/lefse/tax_s_lefse_M1_sinovac_sVNT_60percent_binary_group_w.lefse.in \
data/species.onemonth.data.snv.lefse_species.txt
```

### Extended figure 2a
```{r, fig.width=8, fig.height=8}
lefse <-
    read_tsv("data/species.onemonth.data.snv.lefse_species.txt",
             col_names=c("species", "v1", "group", "LDA_score", "p.value")) %>%
filter(!is.na(group)) %>%
mutate(LDA_score=case_when(
    group==0 ~ (-LDA_score),
    TRUE ~ LDA_score)) %>%
mutate(group=factor(group, levels=c("0", "1")))

fig2a <- ggbarplot(
    lefse, x = "species", y = "LDA_score",
    fill = "group",
    color = "white",
    sort.val = "asc",
    sort.by.groups = TRUE,
    ylab= FALSE,
    rotate = TRUE,
    legend.title = "sVNT_60percent_binary_group") +
ggtitle("LEfSe + M1 + SinoVac + sVNT_60percent_binary_group") +
ylab("LDA SCORE (log 10)") +
scale_fill_manual(breaks=c("0", "1"), labels=c("Low responders", "High responders"),
                  values=c("0"="#E69F00", "1"="#0072B2"))

print(fig2a)
ggsave("figures/Extended_figure_2a-species_lefse_M1_sinovac_sVNT_60percent_binary_group_py.pdf",
       fig2a, width=8, height=8)
```


## BioNTech
### LEfSe analysis with BioNTech group
```{r}
tax_s_l_m1_biontech_sVNT_binary_group <-
    tax_s_l_272S %>%
    filter(TimePoint=="M1") %>%
    filter(Vac_Group=="BioNTech") %>%
    select(sample_id, Species, Abundance, sVNT_binary_group) %>%
    group_by(Species) %>%
    mutate(Species_abun_sum=sum(Abundance)) %>%
    filter(!Species_abun_sum<=0.0) %>%
    select(-Species_abun_sum) %>%
    ungroup()

tax_s_l_m1_biontech_sVNT_binary_group_2 <-
    tax_s_l_m1_biontech_sVNT_binary_group %>%
    select(sample_id, sVNT_binary_group) %>%
    distinct() %>%
    mutate(Species="sVNT_binary_group") %>%
    rename(Abundance=sVNT_binary_group) %>%
    mutate(Abundance=as.numeric(Abundance))

tax_s_l_m1_biontech_sVNT_binary_group_w <-
    tax_s_l_m1_biontech_sVNT_binary_group_2 %>%
    bind_rows(tax_s_l_m1_biontech_sVNT_binary_group %>%
    select(sample_id, Species, Abundance)) %>%
    pivot_wider(names_from=sample_id, values_from=Abundance)
    
print(dim(tax_s_l_m1_biontech_sVNT_binary_group_w))
write_tsv(tax_s_l_m1_biontech_sVNT_binary_group_w,
          "tables/lefse/tax_s_lefse_M1_biontech_sVNT_binary_group_w.tsv")
```

### run LEfSe
```{bash}
lefse_format_input.py \
tables/lefse/tax_s_lefse_M1_biontech_sVNT_binary_group_w.tsv \
tables/lefse/tax_s_lefse_M1_biontech_sVNT_binary_group_w.lefse.in  \
-c 2 -u 1 -o 1000000

lefse_run.py \
tables/lefse/tax_s_lefse_M1_biontech_sVNT_binary_group_w.lefse.in \
data/species.onemonth.data.bnt.lefse_species.txt
```


### Extended figure 2b
```{r}
lefse <-
    read_tsv("data/species.onemonth.data.bnt.lefse_species.txt",
             col_names=c("species", "v1", "group", "LDA_score", "p.value")) %>%
filter(!is.na(group)) %>%
mutate(LDA_score=case_when(
    group==0 ~ (-LDA_score),
    TRUE ~ LDA_score)) %>%
mutate(group=factor(group, levels=c("0", "1")))

fig2b <- ggbarplot(
    lefse, x = "species", y = "LDA_score",
    fill = "group",
    color = "white",
    sort.val = "asc",
    sort.by.groups = TRUE,
    ylab= FALSE,
    rotate = TRUE,
    legend.title = "sVNT_Q1_binary_group") +
ggtitle("LEfSe + M1 + BioNTech + sVNT_Q1_binary_group") +
ylab("LDA SCORE (log 10)") +
scale_fill_manual(breaks=c("0", "1"), labels=c("Low responders", "High responders"),
                  values=c("0"="#E69F00", "1"="#0072B2"))

print(fig2b)
ggsave("figures/Extended_figure_2b-species_lefse_M1_biontech_sVNT_binary_group_py.pdf",
       fig2b, width=8, height=8)
```

## merge two figures into one figure
```{r, fig.width=20, fig.height=10}
library(patchwork)
p <- fig2a + fig2b
print(p)
ggsave("figures/Extended_figure_2.pdf", p, width=12, height=6)
```

